-- SYM-295 — workflows + triggers as first-class data.
--
-- Incremental, additive migration. Does NOT touch 0001_init.sql.
-- Adds:
--   - workflows           — agent configuration record (engine, model,
--                           tool allow/deny, sandbox, prompt template).
--                           Scoped to one of: organization / team / user.
--   - workflow_versions   — immutable snapshots emitted on publish so
--                           historical resolves can replay the exact
--                           config that ran.
--   - workflow_triggers   — event → workflow routing rows. One trigger
--                           per (event, match) pair; the resolver picks
--                           the best match by scope tier + priority.
--   - api_tokens          — stub table. The Worker does not read from
--                           it yet; issuance + auth integration lands
--                           in SYM-296. Pre-created here so the bearer
--                           middleware in Track 2 has a target.
--
-- Conventions match 0001_init.sql:
--   - text() ids generated by the Worker (crypto.randomUUID()).
--   - integer Unix-seconds timestamps.
--   - integer 0/1 booleans.
--   - JSON-array columns stored as TEXT (parsed by callers).

-- ────────────────────────────────────────────────────────────────────
-- workflows
-- ────────────────────────────────────────────────────────────────────

CREATE TABLE workflows (
  id                       TEXT    PRIMARY KEY,

  -- Scope: exactly one of organization_id / team_id / user_id is
  -- non-null. Enforced by the CHECK below. Team and user scopes are
  -- accepted by the schema even though Track 4's UI only exposes
  -- org-scoped workflows in the first cut.
  organization_id          TEXT             REFERENCES organizations(id) ON DELETE CASCADE,
  team_id                  TEXT             REFERENCES teams(id) ON DELETE CASCADE,
  user_id                  TEXT             REFERENCES users(id) ON DELETE CASCADE,

  name                     TEXT    NOT NULL,
  description              TEXT,

  -- Engine / model selection. Engine string maps to a dispatcher
  -- profile on the sandbox-dispatcher side (pi, claude, codex, …).
  engine                   TEXT    NOT NULL DEFAULT 'pi',
  model                    TEXT,
  max_turns                INTEGER NOT NULL DEFAULT 10,
  max_continuations        INTEGER,

  -- Tool / sandbox policy. JSON-encoded arrays stored as TEXT.
  allowed_tools            TEXT,             -- JSON array of strings
  disallowed_tools         TEXT,             -- JSON array of strings
  allowed_domains          TEXT,             -- JSON array of strings
  mcp_servers              TEXT,             -- JSON array of objects
  permission_mode          TEXT,             -- 'ask' | 'allow' | 'deny' | ...
  additional_read_paths    TEXT,             -- JSON array of strings
  additional_write_paths   TEXT,             -- JSON array of strings

  -- Workspace lifecycle hooks. Shell snippets run before / after the
  -- workspace exists. Timeout is a hard ceiling for the whole hook
  -- chain (ms).
  hook_after_create        TEXT,
  hook_before_remove       TEXT,
  hook_timeout_ms          INTEGER NOT NULL DEFAULT 300000,

  -- Liquid template rendered into the agent's first turn. Required —
  -- empty templates would silently produce empty prompts.
  prompt_template          TEXT    NOT NULL,

  -- Bumped on every publish; matches the latest row in
  -- workflow_versions. `draft` workflows have not yet been published
  -- (version may still be 1 if never published).
  version                  INTEGER NOT NULL DEFAULT 1,
  status                   TEXT    NOT NULL DEFAULT 'draft',     -- 'draft' | 'published' | 'archived'
  published_at             INTEGER,

  created_at               INTEGER NOT NULL,
  updated_at               INTEGER NOT NULL,

  -- Exactly one scope owner. SQLite has no XOR, so we count the
  -- non-null columns explicitly.
  CHECK (
    (CASE WHEN organization_id IS NULL THEN 0 ELSE 1 END) +
    (CASE WHEN team_id IS NULL          THEN 0 ELSE 1 END) +
    (CASE WHEN user_id IS NULL          THEN 0 ELSE 1 END) = 1
  )
);

CREATE INDEX idx_workflows_org    ON workflows(organization_id);
CREATE INDEX idx_workflows_team   ON workflows(team_id);
CREATE INDEX idx_workflows_user   ON workflows(user_id);
CREATE INDEX idx_workflows_status ON workflows(status);

-- ────────────────────────────────────────────────────────────────────
-- workflow_versions — immutable snapshot per publish
-- ────────────────────────────────────────────────────────────────────

CREATE TABLE workflow_versions (
  id           TEXT    PRIMARY KEY,
  workflow_id  TEXT    NOT NULL REFERENCES workflows(id) ON DELETE CASCADE,
  version      INTEGER NOT NULL,
  -- Full workflow row serialized as JSON at publish time. The
  -- resolver does not read this today; the runner pins the snapshot
  -- onto a session so historical re-renders are reproducible.
  snapshot     TEXT    NOT NULL,
  created_at   INTEGER NOT NULL,
  UNIQUE(workflow_id, version)
);

CREATE INDEX idx_workflow_versions_workflow ON workflow_versions(workflow_id);

-- ────────────────────────────────────────────────────────────────────
-- workflow_triggers — event → workflow routing rows
-- ────────────────────────────────────────────────────────────────────
--
-- One row per (event, optional match cols, scope filters, action).
-- Resolver picks at most one row per event using:
--   scope_tier DESC, priority DESC, LIMIT 1
-- where scope_tier = 2/1/0 for user/team/org workflows.

CREATE TABLE workflow_triggers (
  id              TEXT    PRIMARY KEY,
  workflow_id     TEXT    NOT NULL REFERENCES workflows(id) ON DELETE CASCADE,

  -- Event surface. Mirrors EventTupleSchema (src/schemas/event.ts).
  event_type      TEXT    NOT NULL,         -- 'session_started' | 'state_entered' | 'state_exited'
                                            -- | 'comment_added'  | 'label_added'   | 'label_removed'
                                            -- | 'assignee_changed'

  -- Event-specific match columns. NULL means "match any". The resolver
  -- treats `col IS NULL OR col = ?` for each one.
  to_state        TEXT,                     -- state_entered: required state id/name
  from_state      TEXT,                     -- state_exited:  required previous state id/name
  label_name      TEXT,                     -- label_added / label_removed
  comment_match   TEXT,                     -- comment_added: regex / contains string

  -- Scope filters. JSON arrays stored as TEXT. NULL means "any".
  team_filter      TEXT,                    -- JSON array of Linear team ids
  project_filter   TEXT,                    -- JSON array of Linear project ids
  label_filter     TEXT,                    -- JSON array of label names that MUST be present
  skip_label_filter TEXT,                   -- JSON array of label names — if present, skip
  assignee_filter  TEXT,                    -- JSON array of user ids (assignee_changed only)

  -- Action dispatched on match.
  action          TEXT    NOT NULL,         -- 'start_session' | 'continue_session' | 'reset_session'
                                            -- | 'stop_session' | 'post_comment'    | 'transition_to'
  action_params   TEXT,                     -- JSON object — passed to the action handler

  priority        INTEGER NOT NULL DEFAULT 0,
  enabled         INTEGER NOT NULL DEFAULT 1,

  created_at      INTEGER NOT NULL,
  updated_at      INTEGER NOT NULL
);

CREATE INDEX idx_workflow_triggers_event    ON workflow_triggers(event_type, enabled);
CREATE INDEX idx_workflow_triggers_workflow ON workflow_triggers(workflow_id);

-- ────────────────────────────────────────────────────────────────────
-- api_tokens — stubbed, no Worker code reads it yet (SYM-296)
-- ────────────────────────────────────────────────────────────────────

CREATE TABLE api_tokens (
  id              TEXT    PRIMARY KEY,
  organization_id TEXT    NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  name            TEXT    NOT NULL,
  -- Hex-encoded SHA-256 of the issued bearer token. The plaintext is
  -- never persisted; issuance returns it once at creation.
  token_hash      TEXT    NOT NULL UNIQUE,
  scopes          TEXT,                     -- JSON array of strings
  created_at      INTEGER NOT NULL,
  last_used_at    INTEGER
);

CREATE INDEX idx_api_tokens_org ON api_tokens(organization_id);
