-- SYM-295 closed-loop observability — every Linear webhook delivery
-- gets one row in `webhook_events` so the dashboard can show:
--   "did the webhook arrive, did the signature verify, did any
--    trigger match, did we dispatch the action, did the agent run?"
--
-- The webhook handler INSERTs a row with `dispatched_action='pending'`
-- right after parsing the body, then UPDATEs it at every exit point
-- (deduped, ignored_envelope, no_match, start_session, error).
--
-- Conventions match 0001_init.sql / 0002_workflows.sql:
--   - text() ids generated by the Worker.
--   - integer Unix-seconds for timestamps, integer ms for latency.
--   - integer 0/1 for booleans.
--
-- `agent_session_id` is FK-by-id only (no REFERENCES) because
-- trigger-initiated sessions are created in the same request that
-- writes this row and we want the link visible even when the session
-- write fails downstream.

CREATE TABLE webhook_events (
  id                   TEXT    PRIMARY KEY,
  received_at          INTEGER NOT NULL,                  -- unix seconds
  organization_id      TEXT             REFERENCES organizations(id) ON DELETE SET NULL,
  webhook_id           TEXT,                              -- Linear's webhookId, when present
  envelope_type        TEXT    NOT NULL,                  -- 'AgentSessionEvent' | 'Issue' | 'Comment' | 'unknown'
  envelope_action      TEXT,                              -- 'created' | 'update' | 'prompted' | ...
  signature_ok         INTEGER NOT NULL,                  -- 0/1
  deduped              INTEGER NOT NULL DEFAULT 0,        -- 0/1
  matched_workflow_id  TEXT,                              -- null on no_match / ignored_envelope
  matched_trigger_id   TEXT,
  dispatched_action    TEXT    NOT NULL,                  -- 'pending' | 'ignored_envelope' | 'no_match'
                                                          -- | 'start_session' | 'no_handler' | 'error'
  agent_session_id     TEXT,                              -- set when start_session dispatches
  error                TEXT,
  latency_ms           INTEGER NOT NULL DEFAULT 0,
  event_summary        TEXT,                              -- short human label, e.g. 'SYM-297 Backlog → Staged'
  raw_body             TEXT                               -- full body (truncated at the read layer)
);

CREATE INDEX idx_webhook_events_received ON webhook_events(received_at DESC);
CREATE INDEX idx_webhook_events_org      ON webhook_events(organization_id, received_at DESC);
CREATE INDEX idx_webhook_events_session  ON webhook_events(agent_session_id);
