-- Org-scoped key/value settings.
--
-- Backs the Agent settings page on the dashboard. The Worker stores
-- string values; per-key validation lives in the route handler, so
-- this table has no CHECK on `key`.
--
-- Curated keys consumed by the runtime today:
--   - 'agent.default_engine'  — fallback engine when no workflow matches
--   - 'agent.default_model'   — fallback model when no workflow override
--   - 'agent.max_turns'       — fallback turn budget
--
-- Other keys (e.g. 'proxy.enabled', 'domain', 'tracker.api_key') may
-- be written via the same endpoint; the Advanced tab in the UI shows
-- them generically. Consumers read by key on demand.
--
-- Conventions match prior migrations:
--   - text() ids generated by the Worker (crypto.randomUUID()).
--   - integer Unix-seconds timestamps.

CREATE TABLE settings (
  id              TEXT    PRIMARY KEY,
  organization_id TEXT    NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  key             TEXT    NOT NULL,
  value           TEXT    NOT NULL,
  created_at      INTEGER NOT NULL,
  updated_at      INTEGER NOT NULL
);

CREATE UNIQUE INDEX idx_settings_org_key ON settings(organization_id, key);
